In [7]:
import pandas as pd

In [9]:
x=pd.read_csv("D:\students.csv",sep=",")
x.loc[10]=[11,'Mary',26,4,90]             #TO ADD VALUES 
print(x)

    ID      Name  Age  Semester  Marks
0    1      Jack   23         8     76
1    2     Frank   21         6     65
2    3       Amy   23         8     70
3    4     Marie   23         8     72
4    5     Steve   19         2     92
5    6     Julia   21         6     68
6    7    Selena   19         2     93
7    8      Mark   20         2     90
8    9     Bryce   21         6     71
9   10  Mallorie   19         2     88
10  11      Mary   26         4     90


In [18]:
x.drop('Age',inplace=True,axis=1)            #DROP A COLUMN
print(x)

    ID      Name  Semester  Marks
0    1      Jack         8     76
1    2     Frank         6     65
2    3       Amy         8     70
3    4     Marie         8     72
4    5     Steve         2     92
5    6     Julia         6     68
6    7    Selena         2     93
7    8      Mark         2     90
8    9     Bryce         6     71
9   10  Mallorie         2     88
10  11      Mary         4     90


In [20]:
x_mean=x["Marks"].mean()
print(x_mean)                       #MEAN

79.54545454545455


In [21]:
#Numpy
import numpy as np

In [24]:
a1=np.arange(20)
a1.shape

(20,)

In [25]:
a1.reshape

<function ndarray.reshape>

In [29]:
arr1=([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20])
arr2=([1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1])

([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20])
([1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1])


In [32]:
sum1=np.add(arr1,arr2)
print(sum1)                           #SUM

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [37]:
print('Mean =',np.mean(sum1, axis = 0))      #MEAN

Mean = [10. 11. 12. 13.]
